---
particles:
  radius: 3 # Радиус окружности для эффектов. Если не нужны - поставить 0
  particle: flame

messages:
  given: 'Тебе выдан сундук!'

drop: true # Можно ли выкидывать кейс
delay: 1.5 # Сколько секунд показывать после открытия всех сундуков
...